### ISSUE TITLE
V3 IsDirty is a string

### ISSUE THREAD

**Issue by PA4WD** [devlooped/GitInfo#243]
## Describe the Bug

In a C# blazor project using ThisAssembly.Git.IsDirty.
After updating to v3
I get the error CS0029 Cannot implicitly convert type 'string' to 'bool'

![GitInfo_bug](https://user-images.githubusercontent.com/15526215/220038611-50a69174-b986-4f37-b062-16c9fd865186.png)

ThisAssembly.Git.IsDirtyString is also empty

## Steps to Reproduce

use IsDirty as a bool

## Version Info

V3.0.2

**Comment by kzu** [comment]
dang, yeah, this is a bug due to a missing [feature in ThisAssembly.Constants](https://github.com/devlooped/ThisAssembly/issues/150)

**Comment by kzu** [comment]
For now, you can workaround the issue by changing your code to:

```csharp
if (bool.TryParse(ThisAssembly.Git.IsDirtyString, out var isDirty) && isDirty)
{
}
```
