### ISSUE TITLE
Version 3.0.5: Error 'ThisAssembly.Git' is inaccessible due to its protection level

### ISSUE THREAD

**Issue by cmiles** [devlooped/GitInfo#273]
## Describe the Bug

In an existing project using version 2.3.0 without problems upgrading to 3.0.5 results in the error 'ThisAssembly.Git' is inaccessible due to its protection level.

I see the same error in a new Console Project adding 3.0.5 - it also reports 'The name 'IsDirtyString' does not exist in the current context'.

## Steps to Reproduce

Create a new Console App
Add GitInfo 3.0.5
Add Console.WriteLine(ThisAssembly.Git.Commit); to the Program.cs
Rebuild the solution (with both new and upgraded projects I tried deleting the bin and obj folders/clean/rebuild with the same results)
I show the errors:
  - 'ThisAssembly.Git' is inaccessible due to its protection level
  - 'The name 'IsDirtyString' does not exist in the current context'

## Expected Behavior

In the project I upgraded to 3.0.5 I wasn't seeing any errors with 2.3.0.

## Version Info

GitInfo Version 3.0.5
VS 2022 Preview, Version 17.6.0 Preview 2.0
net7.0
Windows 11

## Additional Info

In the existing project I upgraded it was a bit difficult to be completely sure that the GitInfo package was the likely source of the error so quickly tried new Console projects - [cmiles/GitInfoV3BugExperiment](https://github.com/cmiles/GitInfoV3BugExperiment).

I did see #92 but adding 'public partial class ThisAssembly { }' in the root namespace didn't seem to have an impact - I haven't had to do that in the past.

Great project!!! Thanks for any help!!!!

**Comment by larcai** [comment]
same issue here

**Comment by walcholi** [comment]
Same for me since I updated from 2.3.0 to 3.0.5

Project: 
- .NET 6 .0
- Windows target
- WPF project

**Comment by tobsil** [comment]
Ran into the same issue. It's working with with version 3.0.4

**Comment by JonathanWheelhouse** [comment]
This is a great package, thanks for your work.

Got the same issue.  i.e. 
error CS0103: The name 'IsDirtyString' does not exist in the current context
error CS0122: 'ThisAssembly.Git' is inaccessible due to its protection level

Project is C# BlazorSasm self hosted .NET 7

**Comment by emroark** [comment]
Had the same problem. Got it working again by adding

`<ThisAssemblyNamespace>System.Reflection</ThisAssemblyNamespace>`

But this is pretty ugly, generates the ThisAssembly into the System.Reflection namespace, and at least one comment in a .targets file says that ThisAssemblyNamespace is unsupported. That said, it works for me, mostly because I already had a `using System.Reflection;` statement in my AssemblyInfo.cs file.

**Comment by luucasgb** [comment]
Got the same problem. Going to try the solution by @emroark

> Had the same problem. Got it working again by adding
> 
> `<ThisAssemblyNamespace>System.Reflection</ThisAssemblyNamespace>`

**Comment by AndrewOsman** [comment]
@luucasgb 

Where does one add
`<ThisAssemblyNamespace>System.Reflection</ThisAssemblyNamespace>`

**Comment by GregEakin** [comment]
@AndrewOsman, In the csproj file, like this:
````
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ThisAssemblyNamespace>System.Reflection</ThisAssemblyNamespace>
  </PropertyGroup>
````

**Comment by ax-meyer** [comment]
Having the same problem here, blocking me from upgrading im multiple projects.

**Comment by OkkeHendriks** [comment]
So `3.0.5` gives me the same error, I have to downgrade to `2.3.0` in order to make it work again,
I have no custom settings, just installed the nuget package.

FYI, the mentioned workaround does work (with `3.0.5`) during debug/release build for me, but not during publish?
> `<ThisAssemblyNamespace>System.Reflection</ThisAssemblyNamespace>`

Used publish profile:
``` xml
<?xml version="1.0" encoding="utf-8"?>
<!--
https://go.microsoft.com/fwlink/?LinkID=208121. 
-->
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <PublishProtocol>FileSystem</PublishProtocol>
    <Configuration>Release</Configuration>
    <Platform>Any CPU</Platform>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <PublishDir>bin\Release\netcoreapp3.0\publish\</PublishDir>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishReadyToRun>false</PublishReadyToRun>
  </PropertyGroup>
</Project>
```

**Comment by kzu** [comment]
I pushed a fix, which is available as 3.0.6 which should also solve this. Sorry folks!

**Comment by kimimaru4000** [comment]
I'm still getting this error message in VSCodium in 3.0.6, though I can compile. `IsDirty` is still returning false when it shouldn't.

**Comment by kzu** [comment]
This issue is for the build error. Please open a new one for incorrect value for IsDirty, perhaps. That would need a full binlog for diagnostics. You can check what `git` commands are being executed and run them yourself manually and see if you get the same dirty/non-dirty behavior via CLI. It might be some git config setting that's actually causing the value to be unexpected.

**Comment by Saibamen** [comment]
Upgraded from `2.3.0` to `3.3.3` and I have this same problem

**Comment by enegs** [comment]
I can't confirm for now because i'm still in 3.3.1 (with correct behavior, btw).

**Comment by digitalsigi** [comment]
I can confirm: 3.3.3 is working. I would recommend to delete all bin & obj folders in this projects and run a clean project.

**Comment by Saibamen** [comment]
@digitalsigi: It was fresh build via Azure DevOps (`msbuild.exe`)

**Comment by FanDjango** [comment]
Create a new Console App **Net Framework** Non-SDK
Add GitInfo 2.3.0
Add Console.WriteLine(ThisAssembly.Git.Commit); to the Program.cs
Works fine.

Upgrade to GitInfo 3.3.3

Result:
'ThisAssembly.Git' is inaccessible due to its protection level

Tried the same sequence with a new Console APP, this time using SDK style .csproj, then GitInfo 3.3.3 is OK.

**Comment by kzu** [comment]
Non-SDK style is for all intents and purposes, legacy stuff. 

I'm open to a PR if you figure out why it fails, but otherwise, this won't be actively worked on.

**Comment by FanDjango** [comment]
That's ok. It took me a while to find this out - so now others can save some time if they stumble across this issue.

It was easy to externalize the GitInfo methods into a separate SDK project and invoke those from the original non-SDK project.

**Comment by kzu** [comment]
I guess I could try issuing a more intuitive build error for that scenario.

Also, you could also create a partial class and make the relevant types public to avoid that? 🤔
